# Generated by Django 5.0.4 on 2024-04-19 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absolute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=250)),
                ('phrase', models.CharField(max_length=250)),
                ('dictionary_meaning', models.CharField(max_length=250)),
                ('examples', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Letters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=250)),
                ('select_letter', models.CharField(max_length=25)),
                ('letter_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=250)),
                ('search_result', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_name', models.CharField(max_length=250)),
                ('title_description', models.TextField()),
                ('title_image', models.ImageField(default='images/firma/firma.jpg', upload_to='images/firma')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_image', models.ImageField(default='images/firma/firma.jpg', upload_to='images/firma')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_firma.title')),
            ],
        ),
    ]
